# Generated by Django 3.2.6 on 2021-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
