# Generated by Django 3.2.6 on 2021-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210805_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
